### ISSUE TITLE
contolling width of popover

### ISSUE THREAD

**Issue by fimperio** [lecar-red/bootstrapx-clickover#1]
Lee,

Thanks for this.  It looks very useful.
Have you put any thought into controlling the width of the popover?

Regards,
Francisco

**Comment by lecar-red** [comment]
that is a good idea, we struggle w/ that all the time. Do you have a syntax in mind?

Maybe:

``` javascript
$('#set-size').clickover({ width: '200px', height: '250px' }); 
```

**Comment by fimperio** [comment]
Sounds good to me.
Once again, thanks for your contribution.
Regards,Francisco

**Comment by lecar-red** [comment]
hi Francisco,

I've added in the above option, but instead of string i used number only so to use it need:

``` javascript
$('#set-size').clickover({ width: 200, height: 250 });
```

If you have a chance give it a try and let me know if it works ok.
