### ISSUE TITLE
option 'hover' with delay

### ISSUE THREAD

**Issue by larsbo** [lecar-red/bootstrapx-clickover#12]
it would be nice, if there will be a hover option!

the popover should be stay some time after hoverout or when mouseover another element that fires the popover.

**Comment by lecar-red** [comment]
Hi Lars,

It could be added pretty easy since the underlying bootstrap popover library supports it. Just curious, why do you need it separately?

Thanks,

Lee

**Comment by larsbo** [comment]
hi lecar-red,
thank you for fast responding! i know the origin popover function from where i found my way to your version :)
but the origin popover also miss the possibility to fire up a popover by hovering over some element and than move with the cursor over to the popover without closing it.

your version is almost what i needed but with a mouseover option instead clicking ;-)

i solved the problem meanwhile without the popover function and build some own easy version.
so if you don't think that this feature makes much sense its ok ;-)

**Comment by lecar-red** [comment]
Hi Lars,

I'd love to see an example of what you are doing. I'm not against adding it just trying to understand. Are you trying to have a clickover that supports both click and hover events or just want to use some of the clickover extras to add an id or use callbacks?

Thanks,

Lee

**Comment by larsbo** [comment]
the first one. either both (click and hover) or just hover. so the popover ('clickover' would be the wrong word in this scenario) opens and now moving the mouse over to it and it still should be there (the origin script closes it immediately) and you could click some link or so.
the possibility for this is already in your script, so i thought my option would make more sense in your script then in the bootstrap one.
the popover should close when you fire up another one, like you already have build, too. perhabs it should also close when the cursor is far enough away from the element and the popover.

i hope i expressed the scenario now slightly better ;-)

**Comment by lecar-red** [comment]
Hi lars,

check out great: http://tshi0912.github.com/bootstrapx-popoverx/

for this feature.

**Comment by larsbo** [comment]
thats exactly what i needed, thank you! (even though i built the functionality by myself meanwhile ;-)
