### ISSUE TITLE
Copy new data of data-content

### ISSUE THREAD

**Issue by kairel** [lecar-red/bootstrapx-clickover#15]
Hi , 
I create a edit form in clickover. I would like save change in data-content.
Example : <input value='value'> and i change the value , i would like save this change in data-content
It's possible ?

Thx

Michael

**Comment by lecar-red** [comment]
Hi Kairel,

I'm not 100% sure what your asking but our product has lots of forms in clickovers. If we need to save part of state there are few ways we do it. One option is to save data as attributes to clickover. 

something like:

``` javascript
/* inside form handler */
$(this).data('popover-ele').$element.attr('form-status', 1); // this could be anything
```

Another option would be to use a function callback for the `data-content` option, this callback could check the server and load data that way. Or do something like this with the `onShown` callback.

The last idea that pops into my head is that you could use an clickover attribute that is the id of the DOM element or data element that loads on one of those callbacks. I'm not sure i have an example sitting around to show.

HTH,

Lee

**Comment by kairel** [comment]
Hi , 
Thanks for your answer.I've use onHidden and onShown like this:

```
$('[rel=fqdn]').clickover
placement: 'bottom'
content: ' '
onShown: ->  
  $('.popover-content').empty()
  this.$element.next('.fqdn-clickover').children('table').clone().prependTo('.popover-content')
  $(document).trigger('reactivate_dynamic_elements')
onHidden: -> 
  this.$element.next('.fqdn-clickover').children('table').replaceWith($('.popover-content').children('table').clone())
```

I don't use data-content , i've create an hidden div and i use it for clone data in popover when show and clone popover in hidden div when hide.

Thx for fast answer.

Michael
