### ISSUE TITLE
Clicking on body in iphone does not close clickover container

### ISSUE THREAD

**Issue by Bhaall** [lecar-red/bootstrapx-clickover#17]
This statement doesn't seem to be firing in an iphone:
"$('body').on( this.attr.click_event_ns, function(e) {..."

So, an open clickover remains open when the body is clicked (or 'touched').

This may be a Safari mobile bug/feature : click events don't bubble all the way up to body.

Is there a solution (or even a hack)?

**Comment by lecar-red** [comment]
Hi Bhaall,

I've noticed that same thing. I looks like I need to add 'touchstart' to that click event handler. I'll hopefully be able to add that tomorrow.

Take Care,

Lee

**Comment by Bhaall** [comment]
Awesome - thank you!

**Comment by Bhaall** [comment]
Maybe something like this?
//modified to add touchstart for mobile support
//this.attr.click_event_ns = "click." + this.attr.me;
this.attr.click_event_ns = "click." + this.attr.me + ", touchstart." + this.attr.me;

**Comment by lecar-red** [comment]
updated it with touchstart event (jquery likes spaces not commas for multiple event types, go figure :)

Let me know if that works for you Bhaall

**Comment by Bhaall** [comment]
Works as expected in mobile.  Thank you again!!!

**Comment by Bhaall** [comment]
Yes - it works as expected.  I added a comment saying this same thing in
the (was closed) thread, and for some reason that thread was reopened?
Dunno why.

But thanks again!  (My name is 'Lee' also, imagine that.)

_Lee
