### ISSUE TITLE
Close button for clickover will scroll the page to the top.

### ISSUE THREAD

**Issue by MiikaL** [lecar-red/bootstrapx-clickover#18]
If you have a Bootstrap style of close button in the clickover (e.g. <a class="close" data-dismiss="clickover" href="#">&times;</a>), it will scroll the page to the top because of the href="#". This does not happen with Bootstrap controls.

This can be fixed by adding a return false:
<a class="close" data-dismiss="clickover" href="#" onclick="return false;">&times;</a>

However, would be nice to not have to remember it, if it can be easily fixed in the bootstrapx-clickover code.

This issue does not occur if closing the clickover box by clicking outside, or on the original element.

**Comment by lecar-red** [comment]
Hi MiikaL,

I'm sorry but i'm having trouble following, can you post a code example? I think it sounds like a simple solution.

Thanks

**Comment by MiikaL** [comment]
Hi,

It seems that I can't reproduce the problem, even in my production code. Perhaps it was something to do with the Bootstrap/BootstrapX version I had at the time? But in any case, can not reproduce, so its no longer a problem. The example I used to try to reproduce it can be found here: http://jsfiddle.net/9ZSGV/2/
