### ISSUE TITLE
click namespace conflict when using multiple clickover init

### ISSUE THREAD

**Issue by tvpavan** [lecar-red/bootstrapx-clickover#6]
when initializing 2-3 clickovers like  this 
            $('[rel="clickover"]').clickover(); 

the name space for each of them could get the same timestamp from Date() i.e this.attr.click_event_ns could be same. 

Hence with allow_multiple option to 0, we miss $(body) click events because the previous hide will "off" the same namespace on body click event.

I just put a hack around with this.

 this.attr.click_event_ns =   "click."  + this.attr.me + "." + element.id; // Adding the elements id to distinguishing the namespace. 

Not the right solution but works for me.

**Comment by lecar-red** [comment]
boy, that seems like a strange case since `new Date()` uses milliseconds, i wonder if the browser cached that timestamp. 

What browser did you see the incorrect behavior?

**Comment by tvpavan** [comment]
Most Frequent in Chrome ( 19.0)  , Very rarely in IE8,  Not seen in FireFox latest ( 13.0 )

**Comment by lecar-red** [comment]
Let me do an update to change that into `Math.random()` and see if that fixes the problem. I should have time this afternoon

**Comment by lecar-red** [comment]
tvpavan, please give it a test and see if that change helps

**Comment by tvpavan** [comment]
cool! works gr8. We can close this issue.
